Accessibility rules1
elsewhencode/project-guidelines pull request #163
Opened 2021-09-15 10:37 UTC by anya91m

2021-09-30 13:44 UTC, vpanjganj requested changes
I still think the accessibility icon is small

2021-09-30 13:44 UTC, vpanjganj commented on README.md
> +> Web content is [accessibile by default](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML). We compromise this when we build complex features. It's much easier to reduce this impact
accessibile => accessible?

2021-09-30 13:44 UTC, vpanjganj commented on README.md
> +> Web content is [accessibile by default](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML). We compromise this when we build complex features. It's much easier to reduce this impact
from the start, rather than having to re-implement these features later. =>
from the start rather than re-implement these features later.

2021-09-30 13:44 UTC, vpanjganj commented on README.md
> +- Arrange to do regular audits using [lighthouse](https://developers.google.com/web/tools/lighthouse#devtools) [accessibility](https://web.dev/lighthouse-accessibility/) or the [axe DevTools extensio
Agree a minimum => Agree on a minimum

2021-09-30 13:44 UTC, vpanjganj commented on README.md
> +  > **Note:** [some important checks](https://web.dev/lighthouse-accessibility/#additional-items-to-manually-check) must be done manually, eg logical tab order. The above tools list these as manual/g
eg logical tab  => e.g. logical tab

2021-09-30 13:44 UTC, vpanjganj commented on README.md
> +  > These components are highly accessible out of the box
full stop

2021-09-30 13:44 UTC, vpanjganj commented on README.md
> +- Ensure heading order is semantically correct.
the heading

2021-09-30 13:44 UTC, vpanjganj commented on README.md
> +  > Headers convey structure of the page. When applied correctly the page becomes easier to navigate. [Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/heading-order?application
the structure

2021-10-01 11:27 UTC, anya91m commented on README.md
> +> Web content is [accessibile by default](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML). We compromise this when we build complex features. It's much easier to reduce this impact
Amended.

2021-10-01 11:27 UTC, anya91m commented on README.md
> +- Arrange to do regular audits using [lighthouse](https://developers.google.com/web/tools/lighthouse#devtools) [accessibility](https://web.dev/lighthouse-accessibility/) or the [axe DevTools extensio
Amended

2021-10-01 11:29 UTC, anya91m commented on README.md
> +  > **Note:** [some important checks](https://web.dev/lighthouse-accessibility/#additional-items-to-manually-check) must be done manually, eg logical tab order. The above tools list these as manual/g
Amended.

2021-10-01 11:30 UTC, anya91m commented on README.md
> +  > These components are highly accessible out of the box
Amended.

2021-10-01 11:31 UTC, anya91m commented on README.md
> +- Ensure heading order is semantically correct.
Amended.

2021-10-01 11:31 UTC, anya91m commented on README.md
> +  > Headers convey structure of the page. When applied correctly the page becomes easier to navigate. [Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/heading-order?application
Amended.

2022-02-03 11:41 UTC, cWillow requested changes

2022-02-03 11:41 UTC, cWillow commented on README.md
> +### 10.2 Basic accessibility rules to add to your project:
Change to "Some basic accessibility rules"

2022-02-03 11:41 UTC, cWillow commented on README.md
> +  > Headers convey structure of the page. When applied correctly the page becomes easier to navigate. [Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/heading-order?application
Please include a link to the rest of the rules at the bottom of this section - something along the lines of `More accessibility rules can be found [here](https://dequeuniversity.com/rules)`

2022-02-03 11:56 UTC, cWillow requested changes

2022-02-03 11:56 UTC, cWillow commented on README.md
> +  > Inaccessible link elements pose barriers to accessibility.[Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/link-name?application=AxeChrome#)
This link and the similar ones below don't seem to work.
I think you need to remove the query param `?application=AxeChrome#` 
However also just realised that `/4.3/` is now out dated so this should probably link to `https://dequeuniversity.com/rules/axe/4.4/link-name`

2022-02-04 11:52 UTC, anya91m commented on README.md
> +### 10.2 Basic accessibility rules to add to your project:
Amended and updated

2022-02-04 11:52 UTC, anya91m commented on README.md
> +  > Headers convey structure of the page. When applied correctly the page becomes easier to navigate. [Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/heading-order?application
Thanks for noticing these. Have updated these now

2022-02-04 11:53 UTC, anya91m commented on README.md
> +  > Inaccessible link elements pose barriers to accessibility.[Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/link-name?application=AxeChrome#)
Thanks for noticing this have updated these now

2022-02-04 12:00 UTC, cWillow commented on README.md
> +  > Inaccessible link elements pose barriers to accessibility.[Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/link-name?application=AxeChrome#)
Nice! They are still linking to the older version 4.3 though. Maybe we should remove these links? Axe seem to release new versions of their rules relatively often, and the link at the bottom should take them to the latest list. Let me know what you think!

2022-02-04 12:04 UTC, cWillow requested changes

2022-02-04 12:04 UTC, cWillow commented on README.md
> +- Provide alternative text for images .
There's a space before the full stop here that needs removing

2022-02-04 12:04 UTC, cWillow commented on README.md
> +  > Screen readers have no way of translating an image into words that gets read to the user, even if the image only consists of text. As a result, it's necessary for images to have short, descriptiv
Need a space before `[Read more..`

2022-02-04 12:04 UTC, cWillow commented on README.md
> +  > Inaccessible link elements pose barriers to accessibility.[Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/link-name)
Need a space before `[Read more..`

2022-02-04 14:45 UTC, anya91m commented on README.md
> +  > Inaccessible link elements pose barriers to accessibility.[Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/link-name?application=AxeChrome#)
Agree about the links. I've removed these and updated PR so that they can be referred to in general link provided at the end of section.

2022-02-04 14:45 UTC, anya91m commented on README.md
> +- Provide alternative text for images .
Amended

2022-02-04 14:45 UTC, anya91m commented on README.md
> +  > Screen readers have no way of translating an image into words that gets read to the user, even if the image only consists of text. As a result, it's necessary for images to have short, descriptiv
Amended

2022-02-04 14:45 UTC, anya91m commented on README.md
> +  > Inaccessible link elements pose barriers to accessibility.[Read more on this rule here](https://dequeuniversity.com/rules/axe/4.3/link-name)
Amended

2022-02-07 15:31 UTC, cWillow approved these changes

2022-02-07 15:31 UTC, vpanjganj approved these changes

2022-02-07 15:31 UTC, merged

2026-08-18 05:56 UTC, rkcom5765-boop reviewed
Jjk